name: Build Docker Image and Push to Evolution Artifact Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CR_URI: hack-archive.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}

      - name: Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/testops-copilot-backend:${{ github.sha }}
          file: ./backend/Dockerfile
          context: ./backend

      - name: Build and push frontend image to Evolution Artifact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/testops-copilot-frontend:${{ github.sha }}
          file: ./frontend/my-react-flow-app/Dockerfile
          context: ./frontend/my-react-flow-app
          
      - name: Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/testops-copilot-agent:${{ github.sha }}
          file: ./backend/Dockerfile
          context: ./backend